### ISSUE TITLE
Cygwin

### ISSUE THREAD

**Issue by viig99** [wbond/sublime_terminal#1]
how can i add support to start cygwin mintty terminal ?

**Comment by rodrigotomonari** [comment]
To use mintty, install "chere" using cygwin setup and use the following cofiguration:

{
    "terminal": "c:\\cygwin\\bin\\mintty.exe",
    "parameters": [
        "-e",
        "c:\\cygwin\\bin\\bash.exe",
        "-c",
        "/bin/xhere /bin/bash.exe"
    ]
}

**Comment by pencilboy99** [comment]
When I do this I get the message "set_prompt" command not found. Also it doesn't source my bashrc and I can't source it manually.

**Comment by twolfson** [comment]
@pencilboy99 What's the configuration you are using?

**Comment by pencilboy99** [comment]
I'm okay it's working.
