### ISSUE TITLE
iTerm.sh opening multiple windows

### ISSUE THREAD

**Issue by facelessuser** [wbond/sublime_terminal#10]
On the first time the Terminal plugin opens iTerm, it opens multiple windows which is kind of annoying.

It looks like it is because of this in iTerm.sh

```if (( $(expr $VERSION '<' 10.7) )); then```

If I bump the version to 10.8, things work as expected when iTerm has not been opened and after.  So I think that is all that needs to be done.

Edit: To be honest, I am not sure why it needs to check the version.  Is there some reason this was originally introduced as such?

**Comment by twolfson** [comment]
We have added tabbed support for iTerm via #72 in `1.8.0`. There should be an incoming update message with instructions on how to use it.

**Comment by chrishough** [comment]
@twolfson thank you
