### ISSUE TITLE
Cmder.exe was not found?

### ISSUE THREAD

**Issue by aolin480** [wbond/sublime_terminal#103]
I use ConEmu all the time, so I wanted to use that, but whenever I put the full path in, it wouldn't work. I saw that you had an example using cmder mini, so I downloaded that and put it in C:\Program Files\cmder_mini\Cmder.exe I then changed my settings to the following in Terminal

```
{
	// The command to execute for the terminal, leave blank for the OS default
	// On OS X the terminal can be set to iTerm.sh to execute iTerm
	"terminal": "C:\\Program Files\\cmder_mini\\Cmder.exe",

	// A list of default parameters to pass to the terminal, this can be
	// overridden by passing the "parameters" key with a list value to the args
	// dict when calling the "open_terminal" or "open_terminal_project_folder"
	// commands
	"parameters": ["/START", "%CWD%"]
}
```

I have restarted sublime text 3 a dozen of times, but it always comes up as `Terminal: The terminal c:\Program Files\cmder_mini\Cmder.exe was not found` I also tried putting cmder at C:\cmder_mini, but that didn't help either. I also put c:\Program Files\cmder_mini\ in my PATH and just set the settings to `"terminal" : "Cmder.exe"` but that didn't work either. Am I missing something on this? The Cmder.exe has a capital C in it, so that's why I am using that. I changed it to a lowercase c, but nada.

Thanks!

**Comment by twolfson** [comment]
What happens when you open a command prompt and run `C:\Program Files\cmder_mini\Cmder.exe`?

**Comment by aolin480** [comment]
It opens up Cmder.exe just fine. I just double checked my settings, and the path is still correct too. I even stopped and restarted Sublime Text as well.

**Comment by twolfson** [comment]
I have verified that my Windows 7 VM works properly with `Cmder.exe` in the following setup:

```js
{
	"terminal": "C:\\tools\\cmder\\Cmder.exe",
	"parameters": ["/START", "%CWD%"]
}
```

It looks like our code foolishly says "Terminal not found" for any `OSError`. Could you open your Sublime Text terminal (ctrl+`) and see what it says?

https://github.com/wbond/sublime_terminal/blob/1.10.1/Terminal.py#L146-L149

> Note to self: Maybe there's a permissioning issue? (e.g. `Cmder.exe` is set to run as admin only but Sublime Text is non-admin)

**Comment by aolin480** [comment]
Yes, that was the issue :( Totally forgot about looking in the console, but I had ConEmu set to run as admin, and sublime was running as a non-admin. I changed the permissions on Sublime Text to run as administrator ALWAYS and now the terminal has been found. Next up, trying to figure out how to go to the %CWD% in ConEmu, but I am sure I'll dig up something. Thanks for the tip!

**Comment by wbond** [comment]
I think conemu respects the directory the exe is invoked from. In other words, I don't think you should have to do anything special and you shouldn't need any parameters.

**Comment by twolfson** [comment]
Before we consider this issue resolved, we should re-evaluate how we error-out about `OSError` (e.g. if it's `ENOENT`, `ERRSPAWN`, or something else -- not sure what the codes in Python are)

**Comment by aolin480** [comment]
Yeah, with ConEmu I have my User settings file set up like this and it's working great!

```
{
	// The command to execute for the terminal, leave blank for the OS default
	// On OS X the terminal can be set to iTerm.sh to execute iTerm
	"terminal": "C:\\ConEmu\\ConEmu64.exe",

	// A list of default parameters to pass to the terminal, this can be
	// overridden by passing the "parameters" key with a list value to the args
	// dict when calling the "open_terminal" or "open_terminal_project_folder"
	// commands
	"parameters": ["-dir", "%CWD%"]
}
```

**Comment by twolfson** [comment]
Looked into how Python handles these error codes. It looks like there's `ENOENT` for not finding the file and the permission issue we had was represented as `EIO`

```
[WinError 2] The system cannot find the file specified
error: Terminal: The terminal C:\tools\cmder\Cmder2.exe was not found
reloading Packages/User/Terminal.sublime-settings
[WinError 5] Access is denied
error: Terminal: The terminal C:\tools\cmder\Cmder.exe was not found
>>> import errno
>>> errno.EPERM
1
>>> errno.ENOENT
2
>>> errno.EIO
5
```

https://docs.python.org/2/library/exceptions.html#exceptions.OSError

https://docs.python.org/2/library/errno.html#module-errno

On Linux, we get the same `ENOENT` error. However, I think `EIO` is a bit convoluted to cast a wide net with a custom error message for. As a result, I think we should handle `OSError` with `ENOENT` with a custom message but propagate any other messages to the end user. I will be opening a PR to reflect that.
