### ISSUE TITLE
`cd` command executed in wrong iTerm tab

### ISSUE THREAD

**Issue by fritz-c** [wbond/sublime_terminal#105]
When I have one tab open in iTerm with a horizontally split view, and execute `Open in terminal` in Sublime, it opens a new tab correctly, but executes the `cd` command in the bottom pane of the first tab.

**Comment by twolfson** [comment]
What version of iTerm are you using and what are the parameters you have configured `Terminal` with?

**Comment by fritz-c** [comment]
Ah, my apologies. I was using a different plugin that had this bug.

**Comment by twolfson** [comment]
Ah, no worries. Thanks for the quick resolution =)
