### ISSUE TITLE
Look for the terminal executable in PATH

### ISSUE THREAD

**Issue by bazzilic** [wbond/sublime_terminal#106]
According to the source, if the directory is not specified, the plugin looks for the executable in its own directory: https://github.com/wbond/sublime_terminal/blob/master/Terminal.py#L46

To me, this is not the intuitive thing to do. First the plugin should check, whether the executable could be found in one of the location listed in the PATH variable in the system. It could easily be done with a snippet from here: http://stackoverflow.com/a/377028/664178

**Comment by wbond** [comment]
If you look closely at the source, it will look first in the plugin's dir to try to make a match. However, if it is not found there, it is passed as-is to `subprocess.Popen()`, which uses the `PATH`.

This functionality allows for the wrapper scripts that exist.

**Comment by bazzilic** [comment]
Yep, my bad, sorry. Was having troubles with starting the terminal, and as it appeared I made a typo.
