### ISSUE TITLE
Environment Variable Usage

### ISSUE THREAD

**Issue by pencilboy99** [wbond/sublime_terminal#108]
%CYGWIN_HOME% is set to C:\Cygwin64

setting the terminal to "%CYGWIN_HOME%/bin/mintty.exe",
setting the terminal to "`%CYGWIN_HOME%`/bin/mintty.exe"

returns a "not found" error.

**Comment by twolfson** [comment]
We are executing `subprocess.POpen` not a `cmd` shell which handles environment variable interpolation. We handle `%CWD%` via a special case:

https://github.com/wbond/sublime_terminal/blob/1.10.1/Terminal.py#L135-L136

Please specify an absolute path (e.g. `C:\Cywin64\bin\mintty.exe`) or add `%CYGWIN_HOME%/bin` to your `PATH` environment variable.

**Comment by pencilboy99** [comment]
Thanks!

**Comment by pencilboy99** [comment]
It would be sweet, just an fyi, if we could add an enhancement that lets you specify "replacement" variables or something like that so I could sync my terminal settings across machines.

**Comment by twolfson** [comment]
I'm not sure if this applicable to your needs but we support OS specific settings (accessed via "Package Settings -> Terminal -> Settings - More -> OS Specific - User")

**Comment by pencilboy99** [comment]
Sweet!!!! Thank you!
