### ISSUE TITLE
How do i open oh-my-zsh on osx ?

### ISSUE THREAD

**Issue by crapthings** [wbond/sublime_terminal#110]
{
	
	"terminal": "zsh",

}

doesn't work

**Comment by twolfson** [comment]
I think there might be some confusion between a terminal and a shell. A terminal emulates video output for a TTY session with the computer (e.g. `gnome-terminal`, iTerm, OS X's Terminal). A shell is a program that helps the user interface with the terminal (e.g. `sh`, `bash`, `zsh`).

This plugin opens a terminal, not tells it what shell to use (unless that's a parameter supported by the emulator).

To correct your setup, either remove the current configuration or follow your corresponding OS X example:

https://github.com/wbond/sublime_terminal/tree/1.10.1#iterm-on-os-x

Then, to make `zsh` your default shell, in the terminal we can run:

```bash
chsh --shell "$(which zsh)" "$USER"
```

**Comment by crapthings** [comment]
awesome!
now i can open iterm2 > zsh
