### ISSUE TITLE
NameError: name 'ls' is not defined

### ISSUE THREAD

**Issue by Xatenev** [wbond/sublime_terminal#113]
Hello,

I have trouble using the cmder console to perform stuff like **ls** or **git**. I have followed the docs, installed cmder and provided the correct path I think. What might be wrong? Error below.

(Sublime Text 3 on Windows)

Thanks!

```
>>> ls
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'ls' is not defined
```

> {
> 	// The command to execute for the terminal, leave blank for the OS default
> 	// On OS X the terminal can be set to iTerm.sh to execute iTerm
> 	"terminal": "C:\\Users\\xxuserxx\\Downloads\\cmder_mini\\cmder.exe",
> 	"parameters": ["/START", "%CWD%"]
> }

**Comment by wbond** [comment]
You seem to be typing commands into the Sublime Text Console. That is different than what this plugin provides.

This plugin provides key bindings to open another program (such as cmder or powershell) into the folder containing the file or project you are working in.

**Comment by twolfson** [comment]
Closing issue as this seems to be resolved
