### ISSUE TITLE
Cmder: Doesn't work

### ISSUE THREAD

**Issue by THE-Beck** [wbond/sublime_terminal#114]
```
"terminal": "C:\\Program Files (x86)\\cmder\\Cmder.exe",
"parameters": ["/START", "%CWD%"]
```
```
{
  "keys": ["ctrl+alt+t"],
  "command": "open_terminal",
  "args": {
    "parameters": ["-T", "Working in directory %CWD%"]
  }
}
```

Error from Cmder launcher:
```
Unrecognized parameter.
/START <path>
/SINGLE <path>
/REGISTER [USER/ALL]
/UNREGISTER [USER/ALL]
```

**Comment by twolfson** [comment]
The `-T` example in the README is intended for XFCE so you should be able to remove that override.

Can you try running something like `C:\\Program Files (x86)\\cmder\\Cmder.exe /START C:\\Program Files (x86)` from within Cmder to verify it launches without any issues?

**Comment by THE-Beck** [comment]
`C:\\Program Files (x86)\\cmder\\Cmder.exe /START C:\\Program Files (x86)`

Error from Sublime Text:
`Terminal: The terminal C:\Program Files (x86)\cmder\Cmder.exe \START C:\Program Files (x86) was not found`

**Comment by twolfson** [comment]
I meant to run that in the Windows command prompt or Cmder =/

**Comment by THE-Beck** [comment]
Oh sorry xD

```
λ C:\\Program Files (x86)\\cmder\\Cmder.exe /START C:\\Program Files (x86)
'C:\\Program' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by twolfson** [comment]
Hmm, maybe we are missing quotes. Can you try:

```
"C:\\Program Files (x86)\\cmder\\Cmder.exe" /START "C:\\Program Files (x86)"
```

**Comment by THE-Beck** [comment]
`"C:\\Program Files (x86)\\cmder\\Cmder.exe" /START "C:\\Program Files (x86)"`
This one works!

**Comment by twolfson** [comment]
Weird, the CLI execution should be identical from our application. Can you try the setup:

```
"terminal": "C:\\Program Files (x86)\\cmder\\Cmder.exe",
"parameters": ["/START", "C:\\Program Files (x86)"]
```

It won't be `%CWD%` but it will act as a sanity check

**Comment by THE-Beck** [comment]
Still giving me same error.
```
Unrecognized parameter.

/START <path>
/SINGLE <path>
/REGISTER [USER/ALL]
/UNREGISTER [USER/ALL]
```

**Comment by twolfson** [comment]
How strange... Can you provide me a screenshot of what you are seeing?

**Comment by THE-Beck** [comment]
Sure, [here ](http://imgur.com/9aJyTEE)you go

**Comment by twolfson** [comment]
This is so confusing =X Are there any errors in the Sublime Text console?

**Comment by THE-Beck** [comment]
Nope, I've just fresh installed everything. Everything's working fine.

**Comment by twolfson** [comment]
Let's try removing `/START <path>` from our invocation to see if it will work:

```
"terminal": "C:\\Program Files (x86)\\cmder\\Cmder.exe",
"parameters": []
```

**Comment by THE-Beck** [comment]
Same error.
```
Unrecognized parameter.

Valid options:
/START <path>
/SINGLE <path>
/REGISTER [USER/ALL]
/UNREGISTER [USER/ALL]
```

**Comment by twolfson** [comment]
Okay, well that's progress I guess. Have you set up multiple configurations (e.g. Windows and User)?

**Comment by THE-Beck** [comment]
No, everything is default.

**Comment by twolfson** [comment]
Alright, can you give me OS information so we can explore setting up an environment to reproduce the error?

**Comment by THE-Beck** [comment]
Okay.
```
Windows 8.1 Pro 64bit
Inter(R) Core(TM) i5-4200U CPU 1.60GHz 2.30GHz
8GB RAM
```

**Comment by twolfson** [comment]
Thanks, we will take a look at reproducing the error by the end of the weekend

**Comment by twolfson** [comment]
I took a shot at reproducing the error via an IE VM (IE11, Windows 8.1 via modern.ie) and was unable to reproduce the error.

![selection_225](https://cloud.githubusercontent.com/assets/902488/14480552/c5709106-00ef-11e6-9bd5-073725d4d40c.png)

It sounds like something OS specific is happening but I have no idea what =/

Can you try removing the terminal/parameters overrides and seeing if the command prompt will launch at all?

**Comment by THE-Beck** [comment]
Same error.

I also tried on my laptop. Also having same error. Laptop spec:
> Windows 10 Pro
> Inter(R) Core(TM) i5-4210M CPU 2.60GHz
> 8GB RAM

**Comment by THE-Beck** [comment]
Oh almost forgot this is my packages list:

> BASE 16 Color Schemes
> Better Coffeescript
> Bracket Highlighter
> Emmet
> HTML5
> Jade
> Predawn
> Sass
> Status bar time
> and of course Terminal

**Comment by twolfson** [comment]
Huh? You received the same Cmder error after removing the `terminal/parameters` settings?

**Comment by THE-Beck** [comment]
Yes.

**Comment by twolfson** [comment]
There's definitely something strange going on on your machine as we have nothing in our package that would use Cmder by default =/

https://github.com/wbond/sublime_terminal/blob/c9595e8abba4c16561d4a81c5eab738bfb376757/Terminal.py#L58-L87

I'm out of ideas but there's something that was edited yet we are missing

**Comment by THE-Beck** [comment]
Okay, i'll try dig into it again :)

**Comment by THE-Beck** [comment]
I've moved cmder to different location reinstalled sublime text and suddenly it works. I have no idea what was the problem. I tried few times again still no idea what problem was caused...

**Comment by twolfson** [comment]
Glad to hear the issue has been resolved =)

**Comment by iulo** [comment]
same issue.
