### ISSUE TITLE
git shell support

### ISSUE THREAD

**Issue by jungor** [wbond/sublime_terminal#116]
I have install github for windows(ps: not git for windows), thus having git shell,
can i open a git shell  directly? 
But it seams that the git shell is just windows power shell, along with some profile scripts imported right before the shell starts.

**Comment by twolfson** [comment]
A powershell instance can be invoked via a `.bat` script. Here's our default powershell integration:

https://github.com/wbond/sublime_terminal/blob/1.12.0/Terminal.py#L66-L85

https://github.com/wbond/sublime_terminal/blob/1.12.0/PS.bat

You should be able to get the same invocation running by taking the `git shell` shortcut and copying its content into a `.bat` script (maybe with a `start` call). Then, setting that `.bat` script to your `terminal` in our user settings:

https://github.com/wbond/sublime_terminal/tree/1.12.0#package-settings
