### ISSUE TITLE
Windows Command Prompt (Terminal) Opens with wrong settings

### ISSUE THREAD

**Issue by SherylHohman** [wbond/sublime_terminal#118]
I don't know if this is 
- a Documentation Issue, or 
- a Programmatic Issue..

I have customized default settings (window width, location, colors) for my Command Prompt window.

However, when it is opened from this plugin, it flashes open with my default settings, then changes itself to different settings. 
- Location of window remains, but 
- Width (and buffer width) changes from 80px to 120px, 
- Title no longer shows the directory I'm in, and 
- Background and Text colors change from yellow/darkGrey to Blue/White.

The setting I am most concerned with is the width,
 as this puts about 1/3 of the window off the screen  (which includes the close button).   

How can I indicate that I want to keep my default parameters when Command/Terminal window opens ?
- I am running windows 7 Pro. 
- I usually open using Git Bash from a Context Menu 
- (ie right click on file/folder from XYplorer, or Windows File Explorer -> Git Bash)

Do I use "parameters" in Terminal.sublime-settings ? 
- If so, how?  
- Or what can otherwise be done ?

Thank You

**Comment by twolfson** [comment]
I'm going to guess we are finding PowerShell on your system and firing our default PowerShell launcher:

https://github.com/wbond/sublime_terminal/blob/1.12.0/Terminal.py#L59-L85

https://github.com/wbond/sublime_terminal/blob/1.12.0/PS.bat

https://github.com/wbond/sublime_terminal/blob/1.12.0/PS.ps1

I'm not too familiar with PowerShell but I would guess we should be able to use your defaults if we remove the majority of the `.ps1` contents. To do this, we create a new `.bat` file and `.ps1:

**C:\my\path\to\PS.bat:**

```
start powershell -noexit -ExecutionPolicy RemoteSigned "C:\my\path\to\PS.ps1"
```

**C:\my\path\to\PS.ps1:**

```
cls
```

We might even be able to remove the `.ps1` file altogether but I'm not sure. After that is set up, we set the `.bat` file as our terminal in our Terminal settings:

https://github.com/wbond/sublime_terminal/tree/1.12.0#package-settings

```js
{
    "terminal": "C:\my\path\to\PS.bat"
}
```

If that loses the `git bash`, then try looking at the properties of the context menu shortcut and using the command as `terminal`/`parameters`.

**Comment by SaltPacket** [comment]
Hello, I am having a similiar issue with CMD on Win10 after upgrading from Win8.1. The CMD window no longer respects default settings when launched from this plugin. For settings, I have:


```
{
  "terminal": "cmd",
  "parameters": []
}
```

**Comment by twolfson** [comment]
Currently travelling now. I will take a look at this by the end of next week

**Comment by twolfson** [comment]
@SaltPacket We don't do anything customization at all for `cmd` execution. Can you elaborate further on these default settings (e.g. provide screenshots)?

**Comment by SaltPacket** [comment]
![capture](https://cloud.githubusercontent.com/assets/11310624/18196608/426edc0c-70ea-11e6-8130-24214219542a.PNG)

The window would not position itself in the correct position as specified in the default settings (pictured). That all being said, I have just had a Windows update and that has seemed to fix the issue.

**Comment by twolfson** [comment]
Cool, glad to hear the issue has been resolved =)

**Comment by airtonix** [comment]
For those who use `concfg` via `pshazz` for powershell, you need to do the following:

1. `preferences > browse packages...`
2. edit `./Terminal/PS.ps1`
3. remove the `foregroundcolor` and `backgroundcolor`
4. open terminal
5. `$ concfg import <your desired theme>`

Now your terminal will look the same again when launched from sublime.

**Comment by twolfson** [comment]
@airtonix I would recommend against directly editing the Terminal `PS.ps1` as it will be overwritten on any package updates. Instead people can define their own `.ps1` in the `User` folder (maybe including the `concfg import line) and point to that:

```js
{
  "terminal": "C:\\path\\to\\custom\PS.bat"
}
```

Files should be based on:

https://github.com/wbond/sublime_terminal/blob/1.14.0/PS.bat

https://github.com/wbond/sublime_terminal/blob/1.14.0/PS.ps1
