### ISSUE TITLE
hot key failed when the sublime executation file contains preloading

### ISSUE THREAD

**Issue by yyBeta** [wbond/sublime_terminal#123]
I'm a Chinese user using the sublime on ubuntu 16.04 and i have to follow the instructions in https://github.com/lyfeyaj/sublime-text-imfix to fix the Chinese inputting in the sublime,
But once the Chinese inputting fixed, the hot key for terminal plugin can not work any more.
Is there any solutions? Thanks a lot.

ps:
I changed the subl executation source to 
#!/bin/sh
LD_PRELOAD=/opt/sublime_text/libsublime-imfix.so exec /opt/sublime_text/sublime_text "$@"

**Comment by twolfson** [comment]
New keyboard shortcuts can be added via "Preferences: Key Bindings - User" in the Command Palette. Our default command bindings can be found here:

https://github.com/wbond/sublime_terminal/blob/1.12.0/Default%20(Linux).sublime-keymap
