### ISSUE TITLE
I can't open the 64-bit PowerShell as default in my win10

### ISSUE THREAD

**Issue by czmecho** [wbond/sublime_terminal#126]
my user setting:
{
	"terminal": "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",
	"parameters": []
}
when I open the terminal ,it show the result:
![](http://ww1.sinaimg.cn/large/7df5111fgw1f6fodtaq7dj20uj0am0y4.jpg)
while I want to use the BashOnWindows,only I can use the 64-bit PowerShell
how can i fix the problem?

**Comment by twolfson** [comment]
This is likely Sublime Text is launching without the proper environment and the subprocess isn't receiving that. Is `bash` normally on your `%PATH%` environment variable?

**Comment by czmecho** [comment]
what't does is mean  bash is  normally on your %PATH% environment variable?
I can run the bash in the powershell normally.

**Comment by twolfson** [comment]
The `%PATH%` environment variable is how Windows normally resolves programs (e.g. if there's a folder with `bash.exe` in the `%PATH%`, then Windows will find/run `bash.exe` from that folder). Can you type `echo "%PATH%"` in a terminal launched outside of Sublime Text and one launched via Sublime Text and paste the results here?

**Comment by czmecho** [comment]
@twolfson 
![](http://ww3.sinaimg.cn/large/7df5111fgw1f6gyi50tiwj20v508l786.jpg)
![](http://ww2.sinaimg.cn/large/7df5111fgw1f6gyi5x9g8j20x90j745n.jpg)

**Comment by twolfson** [comment]
Hmm, maybe double quotes isn't the proper syntax on Windows. It should look like `C:\...;C:\...`. Can you try again with `echo '%PATH%'` and `echo %PATH%`?

**Comment by czmecho** [comment]
@twolfson 
![](http://ww4.sinaimg.cn/large/7df5111fgw1f6hfq307c1j21bx0m57lj.jpg)

**Comment by twolfson** [comment]
Ah, right -- PowerShell syntax. Hmm, those both have the same path. And you are sure `bash.exe` can't be found in which Window?

**Comment by czmecho** [comment]
@twolfson I have added  the folder where the bash.exe exist.
![](http://ww3.sinaimg.cn/large/7df5111fgw1f6hgdbpbgaj21e30j4qh9.jpg)

**Comment by twolfson** [comment]
Ah, so it sounds like this problem has been resolved then. Closing this ticket.

**Comment by czmecho** [comment]
@twolfson the problem isn't  solved.
at first,I have add the folder in  $path .

**Comment by czmecho** [comment]
@twolfson 
![](http://ww3.sinaimg.cn/large/7df5111fgw1f6hh638sftj20uy09wjvw.jpg)

**Comment by twolfson** [comment]
Ah, sorry. It sounded like it was =/

**Comment by czmecho** [comment]
@twolfson yes,it can work in an non Sublime Text launched PowerShell
![](http://ww4.sinaimg.cn/large/7df5111fgw1f6hhy1y8wrj20yk08wjsg.jpg)

**Comment by czmecho** [comment]
@twolfson and it's not the / or \

**Comment by czmecho** [comment]
@twolfson 
![](http://ww3.sinaimg.cn/large/7df5111fgw1f6hi23vht2j21cn0adgrx.jpg)
I try to open the bash on the same folder but with diffrent PowerShell process.

**Comment by czmecho** [comment]
@twolfson and I try to modify the sublime_terminal user setting:
{
"terminal": "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe",
"parameters": []
}
to 
{
"terminal": "powershell.exe",
"parameters": []
}
it happen again.

**Comment by twolfson** [comment]
Can you try the following? We have a custom batch script for PowerShell:

```
"terminal": "PS.bat"
```

**Comment by czmecho** [comment]
@twolfson ![](http://ww4.sinaimg.cn/large/7df5111fgw1f6hiaafxgbj21150hjag2.jpg)

**Comment by twolfson** [comment]
I don't understand what you are attempting to convey with that screenshot =/

**Comment by czmecho** [comment]
@twolfson 
sorry,the Image Hosting have some problem.
![](http://ww3.sinaimg.cn/large/7df5111fgw1f6hid6mn8bj21150hjag2.jpg)

**Comment by wbond** [comment]
@czmecho There shouldn't be a `\` before `PS.ps1`. Did you try and execute `PS.ps1` from a powershell window started via the start menu?

**Comment by czmecho** [comment]
@wbond 
![](http://ww2.sinaimg.cn/large/7df5111fgw1f6hsj7ztcij212g0k8tii.jpg)

**Comment by czmecho** [comment]
@wbond 
![](http://ww4.sinaimg.cn/large/7df5111fgw1f6hsl61cjsj20va0cln3e.jpg)

**Comment by wbond** [comment]
Did you execute `PS.bat` by double-clicking in explorer? That won't work. The Terminal package sets an environmental variable to ensure the path to `PS.ps1` is fully-qualified.

**Comment by czmecho** [comment]
I　run the powershell as Administrator directly from C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe 
it show nothing.
when I change to D:\Documents\soft\Sublime Text\Data\Packages\Terminal
it show the result:
![](http://ww2.sinaimg.cn/large/7df5111fgw1f6ht4g3alaj20uh0ohalt.jpg)
I think it's because it can't load the PS.ps1

**Comment by wbond** [comment]
That error is because you didn't quote a file path with a space in it.

**Comment by czmecho** [comment]
@wbond sorry.
in the powershell I post above,I run the command :set-executionpolicy -executionpolicy unrestricted
and now I can call the bash on powershell launched via Sublime Text.
thanks.
