### ISSUE TITLE
Terminal was not found, but path is correct

### ISSUE THREAD

**Issue by thehig** [wbond/sublime_terminal#137]
I'm running Windows 8, Sublime 3126

I have set my terminal user settings to the following: 

```json
{
	"terminal": "‪C:/Users/David/Documents/cmdr/Cmder.exe",
  	"parameters": ["/START", "%CWD%"]
}
```

However, when I try to open the terminal, I get an error saying the file can't be found. 

I have copied the file name and used sublimes console to mimic the Popen from [here](https://github.com/wbond/sublime_terminal/blob/master/Terminal.py#L144) and the prompt opens. 

```import subprocess; subprocess.Popen("C:/Users/David/Documents/cmdr/Cmder.exe");```

The file URI is definitely correct but the Terminal extension insists that the file is not found. I am experiencing this issue on multiple windows based computers.

**Comment by wbond** [comment]
Did you try backslashes?

**Comment by thehig** [comment]
I did, yes with the same outcome. Works in the sublime console, does not work from the extension

**Comment by thehig** [comment]
If I can do anything to increase the amount of output to assist in debugging, please just let me know.

**Comment by wbond** [comment]
Most likely some sort of OSError is happening when trying to launch: https://github.com/wbond/sublime_terminal/blob/master/Terminal.py#L146-L149.

The typical cause for this is the terminal not being found, so I think that error message is masking the real error. You could try to print the exception in that `except` block and see what it says.

A good enhancement would be to explicitly check for the terminal existing on disk, and then if there is still an OSError, displaying that to the user.

**Comment by thehig** [comment]
I modified the code like so:

![image](https://cloud.githubusercontent.com/assets/96122/19247268/41eeb09e-8f22-11e6-8340-9794486bde57.png)

Which outputs 
```
reloading plugin Terminal.Terminal
‪C:\Users\David\Documents\cmdr\Cmder.exe is a file:  False
[WinError 2] The system cannot find the file specified
error: Terminal: The terminal ‪C:\Users\David\Documents\cmdr\Cmder.exe was not found
```

My current working suspicion is that it could be a windows permissions error. I've also tried hard-coding in a URL to a file that exists in my `C:\\` and that also returns `isFile()` of `false`

**Comment by thehig** [comment]
Bizarely, `os.path.isfile` returns false, but python is capable of reading the file from the sublime console

![image](https://cloud.githubusercontent.com/assets/96122/19247633/0713af9a-8f24-11e6-86c0-c283f17423f3.png)

**Comment by thehig** [comment]
I did some dicking around, and tried to open the cmd prompt to try and read the binary file, basically as I have in the image above. The file open threw a different error:
```
[Errno 22] Invalid argument: '\u202aC:\\Users\\David\\Documents\\cmdr\\Cmder.exe'
```
There was a unicode control character hiding at the beginning of the string. By deleting the beginning of the line, from the start up to the `C:` and retyping it, it now works. I don't know where that unicode character came from, but with it gone the terminal seems to be working.

If memory serves, I copied the file name directly from the file properties 'security' tab.

Anyway, thanks for the help, this sorts this out

**Comment by newflydd** [comment]
thehig，How did you solved this. I confront the same problem like this.
`{
  // Replace with your own path to cmder.exe
  "terminal":"D:\\programes\\tools\\cmder\\cmder.exe",
  "parameters": ["/START", "%CWD%"]
}`
but it says terminal not found, and the path is correct.

**Comment by twolfson** [comment]
@newflydd Troubleshooting to check:

- Appropriate settings file is being updated
- Try running `terminal` command in a command prompt

**Comment by thehig** [comment]
In my case the solution was to check for hidden characters, invisible
unicode

**Comment by Milad137** [comment]
had the exact same issue. I copied the address from properties of cmd.exe,
got this error.
Solution: JUST type the cmd address:
c:\\windows\\system32\\cmd.exe
