### ISSUE TITLE
Make Terminal(windows Terminal)  like ubuntu.

### ISSUE THREAD

**Issue by MamoniAL** [wbond/sublime_terminal#143]
Someone make a package to heal and correct the terminal. This means to make all commands aviable
like "nano"  "vi"  "touch"  remove copy paste file. This will be great we don't have to install   UBUBTU we have SublimeText that work exactly like ubuntu, so we make files on sublime text that better than editor text on linux. Who knows to create this package please do it. Thank u.

**Comment by twolfson** [comment]
There are tools like MinGW and `gow` for adding UNIX tools to Windows. This project focuses solely on opening terminals, not adding additional interfaces. Please see the links below for getting those set up with Windows command prompt itself:

http://www.mingw.org/

https://github.com/bmatzelle/gow

**Comment by MamoniAL** [comment]
thank u man i will see this tool and hope gonna work.
