### ISSUE TITLE
<SIS> install.sh sis-1.3.6 installer  Can I install <SIS> on sublime_text?

### ISSUE THREAD

**Issue by MamoniAL** [wbond/sublime_terminal#146]
I need <SIS> becouse i am a student my  lap-top  is with windows  10 .  Can i install SIS with install.sh or show me the way please. thank u all

**Comment by twolfson** [comment]
Closing issue without assistance due to being unrelated to project and ignoring previous warnings (#143, #144, #145)

**Comment by MamoniAL** [comment]
Stupid muther fucker  fuuuuu  retard boy. I am making an issue here u tard fuck close theat.  Fuck this site git hub on your mom and i am out off here muther fucker.

**Comment by wbond** [comment]
@MamoniAL You are unwelcome on this bug tracker. @twolfson has made a point of trying to help you, but you've ignored him. Please don't post again.
