### ISSUE TITLE
windows CMD terminal setting for sublime text 3!

### ISSUE THREAD

**Issue by xgqfrms-GitHub** [wbond/sublime_terminal#147]
**windows CMD terminal setting for sublime text 3!**

[https://gist.github.com/xgqfrms-GitHub/f9273addd6c9f9d4a9556be6a4886161](https://gist.github.com/xgqfrms-GitHub/f9273addd6c9f9d4a9556be6a4886161)

**Comment by xgqfrms-GitHub** [comment]
test OK!
**but title doesn't work at all!**

**Comment by twolfson** [comment]
The gist you linked to has a lot of misinformation in it. Terminal Settings should not have any key binding information in them (e.g. `keys`, `command`) as those aren't respected -- that should be done for any key bindings. To set a default title for all new `cmd.exe`, the settings would look like:

```js
{
    "terminal": "C:\\Windows\\System32\\cmd.exe",
    "parameters": ["/START", "%CWD%", "/TITLE", "Hacker's Bash"]
}
```

General settings reference: https://github.com/wbond/sublime_terminal/tree/1.14.0#package-settings

Key binding reference: https://github.com/wbond/sublime_terminal/tree/1.14.0#custom-parameters

For setting it as a key binding only, that would look like:

```js
{
  "keys": ["ctrl+alt+t"],
  "command": "open_terminal",
  "args": {
    "parameters": ["/START", "%CWD%", "/TITLE", "Hacker's Bash"]
  }
}
```
