### ISSUE TITLE
CommandNotFoundException

### ISSUE THREAD

**Issue by golamSaroar** [wbond/sublime_terminal#151]
I get the following every time I open Terminal on ST3 (Windows10).

```
\PS.ps1 : The term '\PS.ps1' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ \PS.ps1
+ ~~~~~~~
    + CategoryInfo          : ObjectNotFound: (\PS.ps1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

```

It doesn't stop me from doing my work. I get this in the immediate next line:
**PS C:\xampp\htdocs\laravel>**

But I can not use some other commands like 
**PS C:\xampp\htdocs\laravel>subl "sublime_text_file_name"** 
to open that file from Terminal. All these used to work really well before I upgraded to Version 3. 

I will be grateful if somebody can help me here.

**Comment by twolfson** [comment]
The issue seems to be appearing from the `sublime_terminal_path` environment variable not being found. We introduce this via the code so it shouldn't be a problem:

https://github.com/wbond/sublime_terminal/blob/1.16.0/Terminal.py#L83-L85

How long have you been experiencing this issue for?

**Comment by golamSaroar** [comment]
I have been experiencing this issue since I upgraded to Sublime Text 3 on Sunday.

Can you tell me how can I fix this?

**Comment by twolfson** [comment]
Hmm, we introduced a change to how we handle environment variables on Sunday so that might be linked with the issue. What currently happens when you try using Terminal in Sublime Text 2 after the package upgrades?

**Comment by twolfson** [comment]
After doing some local exploring, it looks like `putenv` doesn't modify `os.environ` so our update isn't picking up the patched `environ`. I'm going to explore fixing this properly

**Comment by twolfson** [comment]
Alright, we introduced a patch in `1.16.1`. Powershell support should be back to functional once Package Control sees the change and it downloads locally to your Sublime Text instance. Thanks for reporting bug report =)

**Comment by golamSaroar** [comment]
Thanks a lot :)
