### ISSUE TITLE
Run Powershell in window 10 as administrator

### ISSUE THREAD

**Issue by joel611** [wbond/sublime_terminal#153]
What should i put in parameter to enforce it open powershell as administrator?

**Comment by twolfson** [comment]
I believe running Sublime Text in Administrator mode should work but that's likely a poor solution due to it giving Admin rights to all plugins =/ Going to look up Powershell documentation...

**Comment by twolfson** [comment]
It looks like it can be done via `-Verb runAs` when starting Powershell:

http://stackoverflow.com/a/7691218

To set that in the invocation, extend our `PS.bat` script and add `-Verb runAs` to it. Then update your Terminal settings to point to that new `PS.bat`:

```
start powershell -noexit -ExecutionPolicy RemoteSigned -Verb runAs "%sublime_terminal_path%\PS.ps1"
```

https://github.com/wbond/sublime_terminal/blob/1.16.1/PS.bat
