### ISSUE TITLE
Powershell instead of command prompt

### ISSUE THREAD

**Issue by NikhilDoWhile** [wbond/sublime_terminal#158]
I am using windows-10, and When I try to open terminal in ST-3 then instead of command prompt, powershell open. How can I instead open command prompt ?

**Comment by wbond** [comment]
Check out https://github.com/wbond/sublime_terminal#examples.

In short, set the `terminal` setting to the path to `cmd.exe` on your machine.

**Comment by NikhilDoWhile** [comment]
From Sytem/path ? Or from some where inside the Sublime Text ? 
Does Cmder mean command prompt ?

**Comment by wbond** [comment]
The absolute filesystem path to the terminal program you want to run. `cmder.exe` is a specific terminal program. It sounds like you want to run `cmd.exe`, not `cmder.exe`.

**Comment by NikhilDoWhile** [comment]
From here : 

http://imgur.com/a/2wTU0

??

**Comment by NikhilDoWhile** [comment]
Solved. Add the location of cmd from system

**Comment by Dibbyo456** [comment]
Having the same issue, I tried this, but does not seem to open anything. the path is correct.

```
{
  // Replace with your own path to cmd.exe
  "terminal": "C:/Windows/System32/cmd.exe",
  "parameters": ["/START", "%CWD%"]
}
```
