### ISSUE TITLE
May I change PS.ps1 "$newsize.height = 50" in Settings?

### ISSUE THREAD

**Issue by h1orz** [wbond/sublime_terminal#166]
Is there any way to change "$newsize.height = 50"(PS.ps1) in Settings - User ?
I just want to use default height.
Thanks so much.

Like ?
```PowerShell
$Host.UI.RawUI.WindowSize = New-Object System.Management.Automation.Host.Size(120,24)
```

**Comment by twolfson** [comment]
I'm still not 100% of the reason we have `height`/`width` set in our `.ps1` launcher. I'm going to guess Windows doesn't provide sane defaults as mentioned here with respect to colors:

https://github.com/wbond/sublime_terminal/pull/148#issuecomment-264834603

We can use a custom launcher by creating a `.bat` and a `.ps1` file, then pointing to them. Here's a comment on a previous issue with instructions on how to do that:

https://github.com/wbond/sublime_terminal/issues/118#issuecomment-221448529

**Comment by h1orz** [comment]
Got it.
Thx.
