### ISSUE TITLE
Is it possible to trigger a new cmder tab instead of a new window?

### ISSUE THREAD

**Issue by badah** [wbond/sublime_terminal#167]
I'm using the following params to open cmder on Windows:
`"parameters": ["/START", "%CWD%"]`

But I would like to open a new **cmder tab** instead of a new cmder window. Is it possible?

**Comment by twolfson** [comment]
I think this should be possible by adding the parameter `-new_console:a` parameter:

```bash
"parameters": ["/START", "%CWD%", "-new_console:a"]
```

If that doesn't work, then it's mostly finding the right parameter for Cmder.exe and adding that to parameters

Reference:

http://conemu.github.io/en/LaunchNewTab.html#Create_new_tab_from_existing_one
