### ISSUE TITLE
Can't open to current directory in Cmder single instance mode

### ISSUE THREAD

**Issue by mjbain10** [wbond/sublime_terminal#168]
I am currently using the parameters for Cmder for Windows specified in the readme. 

`
  "parameters": ["/START", "%CWD%"]
`

When I try to open Cmder from Sublime it works fine if I have no other Cmder window open. It opens to the CWD as expected. But when I try to open Cmder again (with another Cmder window already open) it does not open a new tab in Cmder. It only brings focus to the previously open Cmder window and does not change the directory.

As far as Cmder settings, I have reset them to default, and just turned on single instance mode. If I turn off single instance mode, and let Cmder open a new window each time, everything works as expected. But I would like this to work with multiple **tabs** in Cmder if possible.

Also, when using the right click > Open Cmder Here function in explorer, I don't have this same problem, and new tabs open to the correct directory.

I've reinstalled Cmder a dozen times and played around with settings and parameters with no luck. I also don't get any errors in the Sublime console so no idea where to go from here. Any ideas?

Thanks!

**Comment by twolfson** [comment]
I believe we resolved the new tab functionality in #167. Can you try out these settings?

```
"parameters": ["/START", "%CWD%", "-new_console:a"]
```

**Comment by mjbain10** [comment]
Doesn't seem to work for me. I made sure I am running Sublime as administrator. 

I actually did some experimenting with parameters such as -new_console, -Exit, -min, and no parameters are having any effect when launched from Sublime it seems.

**Comment by twolfson** [comment]
What happens when you try to run `Cmder.exe` from a command prompt (i.e. environment similar to Sublime and not `Cmder.exe` itself)?

```
Cmder.exe /START some-directory
```

**Comment by mjbain10** [comment]
So I have the same issue when running `Cmder.exe` from cmd. 

When I try to add any command line options like `/START` directly in cmd, I get an "unrecognized parameters" error. The only way I could get Cmder to open in a certain directory is by changing it in the Cmder settings menu, where you can set default commands. And even then I still have the problem where it isn't opening new tabs when i launch via cmd. I can only get the tabs to work via the right click in explorer option.

Looking like this is a cmder issue and not an issue with sublime terminal?

**Comment by twolfson** [comment]
Yea, I think it looks like a Cmder issue as well. My suggestion for next steps is find out what command the explorer context menu is running and try to get that working in a command prompt

I'm going to pre-emptively close this issue as a `wontfix`

**Comment by g-akshay** [comment]
Any update from Cmder about fixing this?
