### ISSUE TITLE
Package does not work with elementary OS with modified key bindings

### ISSUE THREAD

**Issue by fx86** [wbond/sublime_terminal#173]
I'm using this package on Sublime Text 3 on Elementary OS. 
With the default key bindings, I was seeing an error popup but ever since I modified it to shortcuts for eOS,  I don't see those either. So no terminal and no errors now. 

Help ?

 ```
[
	{ "keys": ["ctrl+shift+t"], "command": "pantheon-terminal" },
	{ "keys": ["ctrl+shift+alt+t"], "command": "pantheon-terminal_project_folder" }
]
```

**Comment by twolfson** [comment]
The original key bindings should be to `open_terminal`, not `pantheon-terminal`. It's the `terminal` command which determines the executable to launch.

We have had a patch open for Elementary OS but it hasn't yet been landed

In the interim, we can set up our Pantheon Terminal via Package Settings as documented here:

https://github.com/wbond/sublime_terminal/tree/1.17.0#package-settings

```js
{
  "terminal": "pantheon-terminal"
}
```

**Comment by fx86** [comment]
Thanks for the quick response. I did that but I'm not able to open the Terminal in the folder where the file is located.

**Comment by twolfson** [comment]
Our program only opens folder, it won't run files in a terminal. For running files in a terminal, please see other options like:

- Sublime Text build system
- https://packagecontrol.io/packages/Shell%20Exec
- https://packagecontrol.io/packages/Console%20Exec

**Comment by fx86** [comment]
Let me clarify: 

I don't want to open files, I want to open the Terminal -- in the folder -- where the file is located.

**Comment by twolfson** [comment]
It feels like we're talking past each other. Could you restate your current setup, the error/issue you're encountering, what you'd expect to happen, and a screenshot of the issue?
