### ISSUE TITLE
iTerm2 + Fish shell support

### ISSUE THREAD

**Issue by kbrgl** [wbond/sublime_terminal#176]
It appears that Terminal does try to detect if Fish is used, but does this using $SHELL and doesn't seem to support setting shell via the iTerm2 preferences.
Are there any plans to support this?

**Comment by kbrgl** [comment]
This might be possible by using AppleScript to click the Edit > Clear Buffer item in the menu.

This is also shell-agnostic, since it uses iTerm's own facility for clearing the screen rather than resorting to shell-specific commands.

**Comment by twolfson** [comment]
Changing a user's default shell is typically managed via `chsh`. Please try:

```bash
chsh -s /path/to/fish
```
