### ISSUE TITLE
Sublime opens PowerShell instead of Cygwin

### ISSUE THREAD

**Issue by hammernaut** [wbond/sublime_terminal#181]
I'm on Windows 10, 64-bit. I dropped mintty.exe into /Sublime Text 3/Packages/Terminal. When open the context-menu to have the file or directory launch in terminal Sublime opens in PowerShell. Is there something I need to change so that the file/directory open in Cygwin instead?

**Comment by twolfson** [comment]
We support alternative terminals via configuration. Here's relevant documentation for configuring Windows and a related Cygwin issue:

https://github.com/wbond/sublime_terminal/tree/1.18.0#cmder-on-windows

https://github.com/wbond/sublime_terminal/issues/1
