### ISSUE TITLE
How can we open terminal in subfolder?

### ISSUE THREAD

**Issue by shivapoudel** [wbond/sublime_terminal#183]
Since I have to use goto definition in sublime I have to include all the files required in WordPress cms but my specific  projects will be inside `wp-content/plugins/<plugin-project>` directory. 

Now in the `<plugin-project>` there can be many directory and sub-directory and if I stick with that directory root files and use `ctrl+shift+t` I can open terminal in that project directory but sometimes I have to edit files located like this too `wp-content/plugins/<plugin-project>/<sub-folder>/<some-file>` then how can I open <project-folder>` but not the sublime project folder.

**Comment by twolfson** [comment]
We provided 2 shortcuts:

- `ctrl+shift+t` which opens in the folder of the current file
- `ctrl+shift+alt+t` which opens in the Sublime Project folder of the current file

Based on your description, it sounds like there's an override being introduced somewhere. Can you recall if you added anything like that?

**Comment by shivapoudel** [comment]
If sublime goto definition would have support the directory to search for then it wouldn't have been the problem.

I know that this package support two above  shortcuts but my need is different. I need a solution and wont prefer to goto project directory means I need additional shortcut. Look the sub project of my need and I wanted to open terminal in a directory where the composer.json file exists.

https://cldup.com/RsbpDU7qxA.jpg

**Comment by twolfson** [comment]
Ah, I see. I can think of a few ways to build that and I'm sure there are plenty of others:

- Use a directory listing like Quick File Creator
    - https://github.com/noklesta/SublimeQuickFileCreator/
- Allow user to define commands that accept parameters like how many levels up
- Something else

I'm going to mark this issue as an enhancement and leave it open for discussion. Unless @wbond has strong opinions otherwise
