### ISSUE TITLE
terminal open only works in Terminal project folder

### ISSUE THREAD

**Issue by v217** [wbond/sublime_terminal#188]
After changing to `tilix` or `/usr/bin/tilix` terminal, instead of the default `gnome-terminal` on ubuntu 17.10. The terminal only opens in Terminal project folder (` ~/.config/sublime-text-3/Packages/Terminal` ). I noticed this bug first after sublime did hang while uninstalling latex-tools.

**Comment by twolfson** [comment]
Can you elaborate on "only opens in Terminal project folder"? I could interpret that as:

- Terminal only functions properly when I'm viewing a file/folder in the Terminal project
- Terminal only launches a terminal window in the Terminal project folder no matter what file is selected
- Something else

**Comment by v217** [comment]
Terminal only functions properly when I'm viewing a file/folder in the Terminal project.
It works only, if I am viewing a terminal sublime-settings json file.

**Comment by twolfson** [comment]
What happens otherwise?

**Comment by v217** [comment]
I get the message:
Terminal: The terminal tilix was not found in a ubuntu native message.

**Comment by v217** [comment]
![screenshot from 2018-02-15 10-12-58](https://user-images.githubusercontent.com/6884591/36248795-ea06b55c-1238-11e8-81d6-8a2e2a674659.png)

**Comment by twolfson** [comment]
Hmm, it's possible `tilix` isn't in your `PATH` properly. Try looking at the Sublime terminal (ctrl+\`) and running `import os; os.environ['PATH']`

**Comment by v217** [comment]
```
>>> import os; os.environ['PATH']
'/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games'
[Errno 2] No such file or directory: '/0/mit internet'
error: Terminal: The terminal tilix was not found
```
Still get the same error message

**Comment by twolfson** [comment]
Can you try running `echo "$PATH"; which tilix` in a terminal to verify it's the same `PATH` and where `tilix` is loaded from?

**Comment by v217** [comment]
```
echo "$PATH"; which tilix
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/v/.local/bin/
/usr/bin/tilix

```

**Comment by twolfson** [comment]
Hmm, everything looks fine to me. Can you copy/paste the config you're using for Sublime Terminal? Also, are any errors that show up in the Sublime console (ctrl+\`) when you run our Sublime Terminal?

**Comment by v217** [comment]
OK, the problem is when I have unsaved scratch files the terminal plugin has no default folder to open

`error: Terminal: No place to open terminal to`

It works fine with other files open, sorry for the wrong info

**Comment by twolfson** [comment]
Ahh, k. It would probably be better if we surfaced that to an alert =/

**Comment by twolfson** [comment]
I've opened https://github.com/wbond/sublime_terminal/issues/189 to hopefully alleviate future issues for other persons. Sorry for the inconvenience =(
