### ISSUE TITLE
Powershell opens with wrong color

### ISSUE THREAD

**Issue by brnrc** [wbond/sublime_terminal#19]
Hi wbond, 
I've installed sublime_terminal through Package Manager and everytime I try to use it with **ctrl+shift+t** my new powershell opens with pink background and yellow text, which is horrible to read.
I saw that the Powershell profile is being set by **PS.ps1** file, with this configuration:

```
$pswindow.foregroundcolor = "DarkYellow"
$pswindow.backgroundcolor = "DarkMagenta"
```

Are those colors really intended to be set in this horrific contrasting duo, or there is really something wrong here?
Thank you.

**Comment by htran-ubed** [comment]
I'm having the same isssue and I find the instructions on how to change it in settings are unclear and lacking.

I changed the colors to Gray and Black in the PS.ps1 file. Why is this not the default?
