### ISSUE TITLE
PowerShell Environment variables.

### ISSUE THREAD

**Issue by adityagulavani** [wbond/sublime_terminal#190]
If I've set some environment variables using SetEnvironmentVariable, I cannot get it back from the PowerShell window opened from sublime text. But, if I open PowerShell from anywhere else (Start menu/cmd), I can get it. 

I've to run PowerShell as Administrator by changing `parameters = []` to `parameters = ["-Verb RunAs"]`

I think I am on the Administrator account (not a user who is also the administrator, I'm the administrator, no user, see P.S.) that is why I'm facing this issue. For normal users (who set up the user account), this issue might not show up.

**Comment by twolfson** [comment]
I don't understand the issue. Can you explain detailed steps to reproduce the behavior and the actual behavior?

**Comment by adityagulavani** [comment]
Sorry for the delay.

Steps to reproduce:
1. On Windows, have an administrator account (if you have created an account with username, on cmd prompt run `net user Administrator /active: yes`
* Administrator account is different from an 'account with a username + administrator privileges'

2. Log in to Administrator account (log out -> you'll see administrator account there -> log in)

3. Set an environment variable using PowerShell's SetEnvironmentVariable cmdlet. [like this](https://stackoverflow.com/a/2571200)

4. Start PowerShell from Sublime Text (which opens by default with your PlugIn)

5. Try to read the variable using GetEnvironmentVariable -> does not work.

6. In the Terminal.sublime-settings, change `parameters = []` to `parameters = ["-Verb RunAs"]`

7. Try to read the variable using GetEnvironmentVariable -> WORKS!

P.S:  `parameters = ["-Verb RunAs"]` will run the opened PowerShell as Administrator. This is really weird because when you are on Administrator account, anything that you opened will be as Administrator.

**Comment by twolfson** [comment]
Does Powershell identify you as the Administrator in both scenarios?

**Comment by adityagulavani** [comment]
Yes. I am not sure how it differs, but I am the Administrator in both cases.

What does the env parameter do?

`// An environment variables changeset. Default environment variables used for the
// terminal are inherited from sublime. Use this mapping to overwrite/unset. Use
// null value to indicate that the environment variable should be unset.
"env": {}`

Default env variables used for terminal are inherited from sublime. Which variables?

**Comment by twolfson** [comment]
Hmm, very strange

The default `env` parameter is all of the environment variables that Sublime Text is initialized with (i.e. `os.environ` in Python; in GNU/Linux, this would be `PATH`, `SHELL`, `USER`, `PWD`, etc):

https://github.com/wbond/sublime_terminal/blob/1.18.0/Terminal.py#L154-L172

**Comment by adityagulavani** [comment]
Correction: you do not need "-Verb RunAs" set as parameter. You need to restart sublime text for the environment variables to show up. 

Somehow, the environment variables are not updated unless you restart sublime. Can you check if you can get environment variables without restarting sublime?

Also, when the shortcut opens terminal (in this case PowerShell) could you open PowerShell directly instead of going through PS.bat? This will avoid any command prompt auto-start variables (command prompt aliases) being sourced to PowerShell.

**Comment by twolfson** [comment]
Unfortunately, all environment variables are inherited from the invocation in the parent environment. We could add something like environment variable overrides but I don't think that's what you're asking for

I believe we need to use `PS.bat` as executing PowerShell directly was causing issues. Feel free to prove us wrong and submit a PR for a version which doesn't require the `.bat` script. Unfortunately, I'm not well versed enough and have other tasks in my queue to make it impractical for me

I'm going to close this PR as it seems like the issue was with how Sublime Text was launched
