### ISSUE TITLE
How to change the background color of the terminal?

### ISSUE THREAD

**Issue by dunderX** [wbond/sublime_terminal#192]

**Comment by twolfson** [comment]
If you're referring to Sublime Text's console, then that's controlled by Sublime Text themes and outside of the scope of this project

If you're referring to a terminal launched via this package, then it should be the same as the default settings on the OS

If you'd like it to be different than the default settings, then it's possible to write a custom launch script which can do those modifications and point to that:

https://github.com/wbond/sublime_terminal/tree/1.18.0#package-settings
