### ISSUE TITLE
[Request] Could there be an option, to have a second terminal?

### ISSUE THREAD

**Issue by bmix** [wbond/sublime_terminal#197]
On Windows, I must use both, CMD.EXE and Cygwin Bash. It would be nice, if I could chose, which one to launch. Could that be added? Thanks.

**Comment by twolfson** [comment]
I don't believe anyone has time to add this feature but it should be easy to add next to the `parameters` fallback in `OpenTerminalCommand`:

https://github.com/wbond/sublime_terminal/blob/1.18.0/Terminal.py#L182-L194

Leaving open and marking as "help wanted"

**Comment by twolfson** [comment]
This has been resolved by @PinataMostGrim in #206 and released in `1.20.0`
