### ISSUE TITLE
Which package is it in Sublime's Package Control?

### ISSUE THREAD

**Issue by CottonEaster** [wbond/sublime_terminal#199]
I can find no entry for any of these strings

- terminal
- sublime_terminal
- sublime-terminal
- browse terminal

I am using SublimeText 3, on Linux.

**Comment by twolfson** [comment]
It should be discoverable via "Terminal".

Package Control doesn't list already installed packages via "Package Control: Install Package" so try "Package Control: List Packages" as well to see if it's already been installed

**Comment by CottonEaster** [comment]
Thank you. Using 'List packages' did indeed reveal the program. (It is annoying, isn't it, that installed programs do not show up _at all_ 'install packages'?) However, and this is why I had not noticed Terminal was installed, the installation had somehow broken. Removing Terminal and reinstalling it seems to have fixed everything.
