### ISSUE TITLE
terminal not opening in correct location

### ISSUE THREAD

**Issue by Tim-at-AST** [wbond/sublime_terminal#201]
When I press the hotkey, the terminal opens at a specific directory but not the directory of the folder or of the project.  I am using Mac OS Mojave 10.14.3, Sublime text 3.1.1.

Any setting I might need to change?

**Comment by Tim-at-AST** [comment]
The problem is that both hotkeys go to the same folder, and the folder is NOT the current folder OR the project folder.

**Comment by twolfson** [comment]
Can you provide us the following information?

- What hotkey are you pressing?
- What are the settings you set up for Sublime Terminal (if any at all)?
- What is the folder you're expecting to open at?
- Can you provide a screenshot of the file sidebar including the currently opened file?

**Comment by Tim-at-AST** [comment]
I pressed shift-command-T
no settings in Sublime Terminal
expecting folder to open at ..../admin
but instead folder opened at $HOME -this is always the case no matter where I am in ST3.  I checked my .bash_profile and it does not alter the directory.

<img width="1680" alt="screen shot 2019-01-29 at 8 41 39 am" src="https://user-images.githubusercontent.com/14029707/51868275-bf6fe900-23a1-11e9-8cae-399bf5db35bd.png">

**Comment by twolfson** [comment]
Could you scroll up to the very top of the sidebar? And are there multiple folders open in this project?

**Comment by Tim-at-AST** [comment]
<img width="1003" alt="screen shot 2019-01-29 at 12 07 07 pm" src="https://user-images.githubusercontent.com/14029707/51876944-6c585f00-23be-11e9-9d00-00669ae01cd0.png">
no, there are no other folders in this project.

**Comment by Tim-at-AST** [comment]
No.  When I restart ST3, opening same (or any other file) the packages seem to load ok, but the unwanted behaviour is still there.  Here is the package loading log from the console.  Have a look at line 3, which says that working directory is "/".  The hotkeys always send me to $HOME, not root (/); but it is interesting anyway, since I opened ST3 by launching it via LaunchBar, after selecting the folder I wanted.  On the other hand, I just tried launching ST3 independently of LaunchBar, and using ST3's own File:Open to open a different folder, but the same unwanted behaviour occurs.

startup, version: 3176 osx x64 channel: stable
executable: /Applications/Sublime Text.app/Contents/MacOS/Sublime Text
working dir: /
packages path: /Users/timothyduke/Library/Application Support/Sublime Text 3/Packages
state path: /Users/timothyduke/Library/Application Support/Sublime Text 3/Local
zip path: /Applications/Sublime Text.app/Contents/MacOS/Packages
zip path: /Users/timothyduke/Library/Application Support/Sublime Text 3/Installed Packages
ignored_packages: ["Vintage"]
pre session restore time: 0.28723
using gpu buffer for window
startup time: 0.386816
environment variables loaded using: /bin/bash -l
reloading plugin Default.arithmetic
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.colors
reloading plugin Default.comment
reloading plugin Default.convert_color_scheme
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.install_package_control
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.rename
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.settings
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin Default.ui
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin ShellScript.ShellScript
reloading plugin 0_package_control_loader.00-package_control
reloading plugin AdvancedNewFile.AdvancedNewFile
reloading plugin auto-save.auto_save
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin SideBarEnhancements.SideBar
reloading plugin SideBarEnhancements.SideBarAPI
reloading plugin SideBarEnhancements.SideBarDefaultDisable
reloading plugin WordCount.WordCount
reloading plugin Terminal.Terminal
plugins loaded
Package Control: No updated packages

**Comment by Tim-at-AST** [comment]
This may be relevant: when I open Terminal.app preferences (under General), there is this message when I click on "Escape Sequence ...":

<img width="779" alt="screen shot 2019-01-29 at 9 03 09 pm" src="https://user-images.githubusercontent.com/14029707/51900424-5d4ace80-2409-11e9-96b1-31a46cb32a2a.png">

The BASH i am using is from MacPorts. 
`GNU bash, version 5.0.2(1)-release (x86_64-apple-darwin18.2.0)`

**Comment by Tim-at-AST** [comment]
Aha!

I just tried switching to the **Default login shell,**  (see the option in the screenshot above) and the ST3 Terminal package works perfectly, sending me to the correct place.  So it must have something to do with me using the new version of BASH.  I don't know how to fix the issue, however.

**Comment by twolfson** [comment]
Ah, interesting! Glad to hear you identified the problem =)

All our shell scripts start with a shebang for `#!/bin/bash`. Maybe that is causing issues when it encounters the custom shell and only executing in a subscript

Can you try duplicating the default `Terminal.sh` but updating `#!/bin/bash` to your custom path (or removing it entirely)?

Here's the file: https://github.com/wbond/sublime_terminal/blob/1.18.0/Terminal.sh

And instructions for how to set a custom script: https://github.com/wbond/sublime_terminal/tree/1.18.0#examples

**Comment by Tim-at-AST** [comment]
OK, I simply edited the `Terminal.sh` in the Packages folder, and used `/opt/local/bin/bash` and now all is working perfectly again.  Problem solved.

**Comment by Tim-at-AST** [comment]
Are you able to delete some of the images I used above which have some of my info in them?  I just realised how 'open' I've been and regret it.

**Comment by Tim-at-AST** [comment]
ok, was able to do it myself.

**Comment by twolfson** [comment]
Wonderful! Glad the issue has been resolved! Thanks for helping work with us through that =)
