### ISSUE TITLE
How to resolve conflict keybindings (in vintage context)?

### ISSUE THREAD

**Issue by ipstone** [wbond/sublime_terminal#204]
Hello, thanks for this very useful package! I am using vintage in sublime, and my vintage setup using <space> as leader key. 

Somehow this created a problem using sublime_terminal, it seems working with vintage, it's always at command mode, therefore everytime I type <space>, the terminal would pause to see what I will press as when using leader key.

Ideas and suggestions for setup to resolve this conflict? Thanks!

**Comment by twolfson** [comment]
I don't entirely follow your explanation. In other keybinding conflict scenarios, we recommend defining keybindings that don't conflict and do what you want. Here's my dump of the built-in Sublime Text keybindings for Vintange:

https://github.com/twolfson/sublime-files/blob/3176.0.0/Packages/Vintage/Default%20(Linux).sublime-keymap

Here's the keybindings we use for Sublime Terminal:

https://github.com/wbond/sublime_terminal/blob/1.18.0/Default%20(Linux).sublime-keymap

New key bindings can be set/override existing ones via "Preferences: Key Bindings" in the Command Palette (alt+shift+p)
