### ISSUE TITLE
"Open Terminal Here" does nothing

### ISSUE THREAD

**Issue by lstroud** [wbond/sublime_terminal#21]
I'm on OSX 10.7.4 with ST2.2207

Niether the keyboard shortcuts or the menu option open a terminal.  

The command is logged: command: open_terminal {"paths": ["/Users/someperson/somefolder"]}, but nothing happens.  Is there anything I can try?

**Comment by twolfson** [comment]
This issue seems to be 3 years old. I am going to optimistically close it. If the issue is still occurring, please re-open it.
