### ISSUE TITLE
Add iTerm script installation instructions

### ISSUE THREAD

**Issue by gohara92** [wbond/sublime_terminal#212]
Maybe I'm a bit of a dum-dum, but I've spent a good 15-20 minutes trying to get iTerm to work before realising there were scripts in this repository.
Should these be installed when you install through package manager (because in my case, they weren't)?
If not, it would be useful to add a line in the documentation telling people to put the scripts in the package folder.
If that's OK, I'd happily do it.

**Comment by twolfson** [comment]
The scripts are installed with the package via Package Control. They probably aren't directly visible as packages use a compressed archive as of ST3 iirc but they are there (otherwise a lot of others would have reported this issue)

Configuration is documented here:

https://github.com/wbond/sublime_terminal/tree/1.23.0#package-settings

The scripts are loaded from the package itself when a relative path is used, otherwise an absolute path can be specified as in some examples

**Comment by gohara92** [comment]
Thanks for your reply.
There must've been some oddity for my installation, as I got the following
`
Traceback (most recent call last):
  File "/Users/georgeohara/Library/Application Support/Sublime Text 3/Packages/Terminal/Terminal.py", line 172, in run_terminal
    subprocess.Popen(args, cwd=cwd, env=env)
  File "./python3.3/subprocess.py", line 819, in __init__
  File "./python3.3/subprocess.py", line 1448, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'iTerm2-v3.sh'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 1052, in run_
    return self.run()
  File "/Users/georgeohara/Library/Application Support/Sublime Text 3/Packages/Terminal/Terminal.py", line 213, in run
    command.run(folders, parameters=parameters)
  File "/Users/georgeohara/Library/Application Support/Sublime Text 3/Packages/Terminal/Terminal.py", line 197, in run
    self.run_terminal(path, terminal, parameters)
  File "/Users/georgeohara/Library/Application Support/Sublime Text 3/Packages/Terminal/Terminal.py", line 177, in run_terminal
    TerminalSelector.get() + ' was not found')
TypeError: get() missing 1 required positional argument: 'terminal_key'
`
when I had the setting "iTerm2-v3.sh" in the config file, prior to putting the iTerm2-v3.sh file from here into `/Users/georgeohara/Library/Application Support/Sublime Text 3/Packages/Terminal`
whether that's something to do with package control I don't know.

Anyway, I suppose this is a record in case anyone runs into a similar issue.
All the best!

**Comment by twolfson** [comment]
Upon re-reviewing the docs, it seems like we've actually built this package to not use a compressed version for its install. i.e. We use `.no-sublime-package` to indicate to avoid doing that

https://github.com/wbond/sublime_terminal/blob/1.23.0/.no-sublime-package

https://packagecontrol.io/docs/submitting_a_package#Step_5

Unsure why Package Control didn't respect that setting. Maybe try uninstalling both Terminal and Package Control, then reinstalling both to see if that resolve it (i.e. should just see files, not a `.sublime-package` file for this repo). If not, then I recommend opening an issue on

https://github.com/wbond/package_control
