### ISSUE TITLE
Allow environment variables in settings

### ISSUE THREAD

**Issue by artt** [wbond/sublime_terminal#214]
For example, I have two computers with different usernames. To set Terminal to open Windows Terminal, I have to set

```
"terminal": "C:/Users/user1/AppData/Local/Microsoft/WindowsApps/wt.exe",
```

for the first computer, and

```
"terminal": "C:/Users/user2/AppData/Local/Microsoft/WindowsApps/wt.exe",
```

for the second computer.

It would be nice to allow things like `~` or `%USERPROFILE%` in the settings.

Cheers!

**Comment by twolfson** [comment]
Kind of tired but thoughts are: If the fork command doesn't already do this, then we'll have to rebuild the behavior ourself which is likely error-prone

A better workaround might be to write your own `.bat` file which runs `C:/Users/%USERPROFILE%/AppData/Local/Microsoft/WindowsApps/wt.exe`

Or `.gitignore` this file

Or something else...
