### ISSUE TITLE
Open in iTerm2 on the current window

### ISSUE THREAD

**Issue by kud** [wbond/sublime_terminal#22]
Hello,

I've always iTerm2 opened and I would like that when I click to "Open in terminal here" it just does "cd %path%" in the current window I was. I've got multiple windows on my iTerm2.

**Comment by twolfson** [comment]
We are exploring options for this in #72 =)

**Comment by twolfson** [comment]
#72 has been landed and released in `1.8.0`. There should be an incoming update message with information on how to use the new option.
