### ISSUE TITLE
Terminal.app opens in default folder

### ISSUE THREAD

**Issue by jmav** [wbond/sublime_terminal#24]
I'm using OS X Lion & macports & bash.

When I use open terminal in sublime, terminal opens in default "profile" path & NOT current open file path.

PROBLEM: To use bash In Terminal.app I needed to set "Shell opens with:" to "/opt/local/bin/bash -l"

IF i set Terminal.app "Shell opens with:" to "default login shell" -> sublime_terminal opens Terminal.app in current opened file loaction.

Hot to fix it?

**Comment by twolfson** [comment]
@jmav Can you verify this problem still exists? Eagerly closing this issue for now.
