### ISSUE TITLE
FiSH doesn't like standard commands

### ISSUE THREAD

**Issue by paradox460** [wbond/sublime_terminal#38]
I'm unsure if this could be fixed using the custom params, but, looking at the docs, It doesn't look like it

FiSH (Friendly interactive shell) doesn't like when a command uses &&, and tends to barf on that. The proper way to run multiple commands in FiSH is with semicolons separating commands.

If possible, a way to specify the command run on terminal open would be greatly appreciated. Thanks

**Comment by twolfson** [comment]
This should be repaired by #40 which will be landed within the next week. Thanks for the bug report!

**Comment by twolfson** [comment]
This has been repaired in `1.6.0` via @kristianj with #40. Thanks for the bug report!
