### ISSUE TITLE
Using open here command on an empty file opens at project folder

### ISSUE THREAD

**Issue by najamelan** [wbond/sublime_terminal#53]
Putting even 1 letter in the file and without saving it, behaves as it should

I'm using ST 2

**Comment by twolfson** [comment]
Can you provide step by step instructions with screenshots of what's occurring? I don't understand the problem entirely and that would help clarify.

**Comment by twolfson** [comment]
It has been 1 month since we replied on this issue but with no updates from the commenters. Closing this issue for now.
