### ISSUE TITLE
Non-default shell "Console2" renders the "Open terminal here..." useless

### ISSUE THREAD

**Issue by GrantSP** [wbond/sublime_terminal#54]
If left to use the default terminal, in my case Powershell, the plugin functions as described. Hotkeys, right-click menu options all work perfectly.
However after changing the terminal to Console2 only the Ctrl+Shift+T hotkeys function, showing the terminal opening in its folder. The right-click menu in both the sidebar and the main editing window result in an error dialog "Terminal: The terminal console2 was not found here."

If I change the terminal to use "cmd" everything again functions as normal.
In all situations I can use these 3 different terminals properly no matter where on the system I start them. They are all in the PATH and all behave as would be expected.

**Comment by twolfson** [comment]
@GrantSP Can you verify that `console2` is in the PATH environment variable from the perspective of Sublime Text? I have found that the environments don't always line up.

Inside of the Sublime Console (`ctrl+\``), please run the following:

```python
import os; print(os.environ['PATH'])
```

**Comment by Patabugen** [comment]
I'm also having this issue.

@twolfson yes, the console2 path is does show up there. Running `console.exe` from `cmd` also works fine.

I've tried putting the full path (with forward slashes and with double back slashes too) into the sublime user settings, after that was when I added console2 to the path.

This makes the console launch, but not in the right directory (and with a spare `cmd` in the background which closes when you close console2.

```
{
	"terminal": "cmd.exe",
	"parameters": [ "/C Console.exe ", "exit "]
}
```

I've tried various params to try and get the directory to be correct (`/c cd %CWD%" && console.exe` for example) but with no joy. Curiously adding ` -d \"%CWD%\"` is landing me in the directory console2 is installed in:

```
{
	"terminal": "cmd.exe",
	"parameters": [ "/C c:\\path\\to\\Console2\\Console.exe -d \"%CWD%\"" ]
}
```

**Comment by twolfson** [comment]
@Patabugen Parameters should be broken up such that we don't need to wrap them in quotes as Python takes care of that. Can you try out:

```
{
    "terminal": "cmd.exe",
    "parameters": ["/C", "c:\\path\\to\\Console2\\Console.exe", "-d", "%CWD%"]
}
```

**Comment by GrantSP** [comment]
Sorry for the passage of time since your request for the PATH.
I've actually dropped using Console2 for the time being, but as my opening post stated Console2 and does show when that command is run.

**Comment by twolfson** [comment]
No worries. Since it's impractical to solve a problem that doesn't exist I will sort out @Patabugen's issues and close up this issue.

If you are having issues with your Console2 replacement, please let us know.

**Comment by Patabugen** [comment]
Ahh! This works: (with a stray cmd window in the background)
```
{
	"terminal": "cmd.exe",
	"parameters": [ "/C", "Console.exe", "-d", "%CWD%" ]
}
```
However this still doesn't:
```
{
	"terminal": "console2.exe",
	"parameters": [ "-d", "%CWD%" ]
}
```

**Comment by twolfson** [comment]
That's great to here. We are making progress =)

It looks like `cmd.exe` is executing `Console.exe` not `console2.exe` though. Have you tried updating the options to:

```js
{
    "terminal": "Console.exe",
    "parameters": [ "-d", "%CWD%" ]
}
```

**Comment by Patabugen** [comment]
Ah sorry the latter was a typo, it doesn't work with either `console2.exe` or `console.exe` (I've tried both with a capital and lowercase C too).

**Comment by twolfson** [comment]
Ah, k. It's possible that Sublime Text was started with a different PATH environment variable than `cmd.exe`. Can you verify `Console.exe` is on the `PATH`?

```
# Run inside of Sublime Text's REPL via Ctrl+`
import os; print(os.environ['PATH'])
```

**Comment by Patabugen** [comment]
The Console2 path is listed in the console after running that command (I'm
afraid! haha)

**Comment by twolfson** [comment]
Damn. Are there any errors in the Sublime Text console when you attempt to open a new terminal?

**Comment by Patabugen** [comment]
Yes! Yes there are!

```
[WinError 740] The requested operation requires elevation
error: Terminal: The terminal console.exe was not found
```

My Console2 was set to always run as administrator, but Sublime Text was
not.

If I make either ST run as admin, or Console2 not run as admin it works
just fine! Running it through cmd.exe works because (I presume) whichever
way cmd.exe runs causes the UAC to pop up (or not pop up if it's disabled),
but ST just fails to request permission.

Drat, sorry I didn't look and notice that sooner!

On 9 July 2015 at 17:47, Todd Wolfson <notifications@github.com> wrote:

> Damn. Are there any errors in the Sublime Text console when you attempt to
> open a new terminal?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wbond/sublime_terminal/issues/54#issuecomment-120065805>
> .
>



-- 
Patabugen

**Comment by twolfson** [comment]
Alright, so it sounds like this issue is resolved =) Closing this issue
