### ISSUE TITLE
How can I run a script in terminal with a  shortkey?

### ISSUE THREAD

**Issue by Tian-Changsong** [wbond/sublime_terminal#56]
Hi, I want to run a script in terminal with a  shortkey, but I have no idea how to set the parameters, for example ,when editing a python script, when ctrl+alt+t pressed, the script runs in gnome-terminal, I have rewrote another command class in Terminal.py to achieve that, but I hate the modification, Is there any better way?

**Comment by twolfson** [comment]
@Tian-Changsong I don't full understand your context. Can you provide an example of the changes you made?

**Comment by wbond** [comment]
Well @Tian-Changsong this package isn't designed to run a command in the terminal, just open a terminal. I think there are some other packages you can look through at https://packagecontrol.io/search/exec that may do what you want.

**Comment by twolfson** [comment]
It has been 1 month since we replied on this issue but with no updates from the commenters. Closing this issue for now.
