### ISSUE TITLE
Default open_terminal key binding overrides "Reopen Closed File"

### ISSUE THREAD

**Issue by XenHat** [wbond/sublime_terminal#57]
I noticed that the keybind shortcut for open_terminal overrides "reopen closed file".

While the terminal plugin is active, the ctrl+shift+T shortcut seems to disappear from the menu, indicating that it is no longer bound to this function.
However, I use the re-open feature a lot, and I am somewhat against overriding a shortcut for a feature that could be considered "core feature".

I could not think of a better shortcut, though.

**Comment by mehdilamaaffar** [comment]
i got the some problem

**Comment by twolfson** [comment]
This is a duplicate of #17. Please follow the discussion there.
