### ISSUE TITLE
Umask issue

### ISSUE THREAD

**Issue by mlsteele** [wbond/sublime_terminal#60]
I'm using Terminal on Ubuntu 13.10 with Sublime Text 3 Stable Build 3059 to launch gnome-terminal. I've been having an issue with my umask which I finally tracked down to this plugin.

If there are no gnome-terminal windows open and I press ctrl+shift+t to launch gnome-terminal, then my umask is set to `000` in that terminal and in _all subsequent_ gnome-terminals until all gnome-terminal windows have been closed.

If there are already gnome-terminal windows open and I pres ctrl+shift+t to launch gnome-terminal, then my umask remains at the default value of `002`.

This method of spawning the terminal is the site of the problem:

    subprocess.Popen(args, cwd=cwd)

**Comment by twolfson** [comment]
Strange, on Linux Mint 17.1 I am not seeing this issue. `umask` returns `0022` in both fresh launch and via Terminal. Can you elaborate on why you think `subprocess.Popen` is the issue?

**Comment by wbond** [comment]
@mlsteele Are you changing your umask in your `.bash_profile`, `.profile` or something similar? Depending on how you are launching Sublime Text, it will have a different environment than your terminal. And then when Sublime Text creates a new process (the terminal), the terminal inherits the environment of Sublime Text.

The most likely way for something like this to happen is if you are launching Sublime Text from a `.desktop` file. You may need to tweak that file to make sure Sublime Text has the `PATH` and other environmental settings you want.

**Comment by mlsteele** [comment]
This bug does not affect me anymore as I no longer use sublime. But if you think it might be affecting others, I'm happy to help.

The behavior has changed a bit, to something less confusing and possibly worse. It is no longer the case that it matters whether there are already gnome-terminal windows open. Whether or not terminal windows are already open, launching a new terminal from outside sublime gets a umask of `002`, but launching a terminal from `sublime_terminal` gets a umask of `000`.

I am now using Ubuntu 15.04. I verified that the issue (the new behavior described above) exists for the sublime_terminal version after just  the package as well as whatever I had a year ago. I have *not* upgraded Sublime Text though and am still on Stable Build 3059.

@twolfson I'm not quite sure what I meant when I said the `subprocess.Popen` is the issue. I added some debug logging to `Terminal.py` and it seems that for me the umask both when `Teriminal.py` is loaded and right before the `subprocess.Popen`, is `000` and that is what the subprocess inherits. It might be worth noticing that I (and all users on this computer) have a default umask of `002`, not `0022`.

@wbond I'm using oh-my-zsh but I really don't think it or anything else in my rc files is manipulating umask. I'm launching sublime from the `subl` command which comes with sublime in `usr/bin/subl`.
```
#!/bin/sh
exec /opt/sublime_text/sublime_text "$@"
```

Hard-coding `TerminalSelector.get` to return `'terminator'` launches Terminator instead of Gnome Terminal but yields exactly the same behavior.

**Comment by twolfson** [comment]
@mlsteele Thanks for taking the time to look into this =) It sounds like the `umask` is more related to Sublime Text itself than Sublime Terminal; we do no tweaking/specication in our module so it's being inherited from somewhere else (either at start time or another plugin).

As a sanity check, you might want to change `/usr/bin/subl` to echo `umask` to make sure it is Sublime Text only

```sh
#!/bin/sh
umask
```

**Comment by spelufo** [comment]
Yes this is an issue with sublime itself. I'm using [this][1] workaround for now. 

[1]: https://gist.github.com/stbuehler/8540197

**Comment by kornieff** [comment]
Solved by adding `umask 0022` to my .bashrc.
