### ISSUE TITLE
LinuxMint (cinnamon)

### ISSUE THREAD

**Issue by denegny** [wbond/sublime_terminal#61]
Hi.

Use "Terminal" package  - https://sublime.wbond.net/packages/Terminal
ST3 -version

terminal dont open

my process is "cinnamon-sessio" without "n"
for example may be use "mdm" (its Mint Display Manager)
but for xface not shure, that true

https://gist.github.com/anonymous/eb28540ca90d186d9c77

**Comment by twolfson** [comment]
This has been patched via #70 in `1.5.0`. Thanks for the bug report =)
