### ISSUE TITLE
open terminal in current project without file open

### ISSUE THREAD

**Issue by isyara** [wbond/sublime_terminal#62]
Hi,

I can not open the terminal in the open project if no file is open !

**Comment by twolfson** [comment]
If you are in a project with a visible folder, then it should open in that project's root folder. What is the behavior you are encountering?

**Comment by twolfson** [comment]
Ah, sorry. I misspoke. It looks like that was working in Sublime Text 2 but it no longer is working in Sublime Text 3. @wbond We should mark this issue with "bug" and "help wanted".

**Comment by twolfson** [comment]
I seem to be experiencing this bug on the latest version. It happens when I open Sublime and have no files visible at all yet have a project in the sidebar. I expect it to open the terminal in the root project folder but nothing happens (with no errors).

Looking into it now.

**Comment by twolfson** [comment]
Found the issue (ST3 always has an active view) and submitting a patch now (verifying view has a file name)

**Comment by twolfson** [comment]
This has been patched/resolved in `1.10.0`. Thanks for the bug report and sorry for the reactive delay =(
