### ISSUE TITLE
Might be Issues about Parameters & Default folder

### ISSUE THREAD

**Issue by leoujz** [wbond/sublime_terminal#64]
(1)"parameters": ["-T", "Custom Window Title"] doesn't work as described in http://wbond.net/sublime_packages/terminal
I still get a default window title.

(2)no response when in a empty unsaved "file", is there a default folder whenever I want to open terminal.

i'm working on ST3

**Comment by twolfson** [comment]
The parameters example is specific to XFCE. If you aren't using XFCE as your terminal, then the title parameter won't work =/

This is stated on the page:

http://wbond.net/sublime_packages/terminal#Custom_Parameters

With respect to your second point, it should open in the root folder of the active project folder. However, this seems to have broken on ST3. Please see #62 for reference.
