### ISSUE TITLE
Problem with Fish shell on OS X

### ISSUE THREAD

**Issue by ghost** [wbond/sublime_terminal#66]
Because it tries to run "cd /asd/qwe && clear", and `&&` apparently is bash syntax and not supported in the excellent fish shell, can you please make this run as two separate commands instead of one liner.

**Comment by benmarten** [comment]
Also had this issue. you can just change the command yourself. Open ~/Library/Application Support/Sublime Text 3/Packages/Terminal/Terminal.sh
and remove one & in line 3!

**Comment by denji** [comment]
You should change the logic behavior

Edit this:
"cd /asd/qwe && clear"

To bring in this mode:
"cd /asd/qwe; and clear"

**Comment by twolfson** [comment]
This is a duplicate of #38. Please refer to the discussion there.

**Comment by twolfson** [comment]
This has been repaired in `1.6.0` via @kristianj with #40. Thanks for the bug report!
