### ISSUE TITLE
Normal cmd terminal on windows

### ISSUE THREAD

**Issue by gonxalusaika** [wbond/sublime_terminal#73]
I'm using this plugin in sublime text 2 on windows.
When I press Ctrl+Shift+T powershell is started. I want to know if it's possible to open the default cmd.exe terminal.
Thanks

**Comment by shivapoudel** [comment]
Preferences > Package Settings > Terminal > Settings - User and use `cmd` as your terminal ;)

```
{
	"terminal": "cmd"
}
```

**Comment by gonxalusaika** [comment]
Thanks Shiva! It works now :D. Sublime needs to be restarted after changing the configuration or the terminal will start on Sublime's User folder.

**Comment by shivapoudel** [comment]
@gonxalusaika I guess we need to restart the a Sublime so for perfect loading of preferences setting ;)
