### ISSUE TITLE
OS-specific sublime-settings file ignored?

### ISSUE THREAD

**Issue by ErichDonGubler** [wbond/sublime_terminal#74]
Love this plugin! I'm having an issue with cross-platform syncing, however - I currently am syncing my `Packages/User` file across Google Drive, so that configuration and plugins are well-integrated in my switches between Linux and Windows installations. With some other plugins (like Sublime itself), one can create settings files of the form:

`<name>[ (<platform>)].sublime-settings`

When I use the following `Terminal.sublime-settings`:

```json
{
	"terminal": "C:\\tools\\cygwin\\bin\\mintty.exe"
}
```

...my terminal changes - I'm able to use Cygwin instead of the default Powershell in Windows 8.1. But when I move this same configuration into `Terminal (Windows).sublime-settings`, I'm reverted back to defaults. Does this plugin support platform-specific settings?

**Comment by twolfson** [comment]
I think this is a great idea. I can't find any plugins that seem to be platform specific for settings except for Sublime itself (typically only keybindings vary). Can you provide a link to another one so we have a basis of comparison?

I see that you also opened #79 to resolve this issue which is nice :+1:

**Comment by twolfson** [comment]
Here are linked to Sublime's default settings that are platform specific:

https://github.com/twolfson/sublime-files/blob/3083.0.0/Packages/Default/Preferences%20%28Linux%29.sublime-settings

https://github.com/twolfson/sublime-files/blob/3083.0.0/Packages/Default/Preferences%20%28OSX%29.sublime-settings

https://github.com/twolfson/sublime-files/blob/3083.0.0/Packages/Default/Preferences%20%28Windows%29.sublime-settings

**Comment by twolfson** [comment]
This issue has been patched via @ErichDonGubler in #79 and released in 1.7.0.
