### ISSUE TITLE
Add shell suport for Git Bash

### ISSUE THREAD

**Issue by shivapoudel** [wbond/sublime_terminal#75]
Since `msygit` is compatiable with more all OS platform. Thus add the terminal suppot Git Bash too as optional.

For windows I am doing:
Create `msygit.bat`
```shell
start sh --login -i
```

After that I am User setting for terminal

```json
{ "terminal": "msygit.bat" }
```

**Comment by twolfson** [comment]
I think this is a fair request to add to the repo. To clarify, what's the behavior without the `.bat`? e.g. The following settings:

```json
{
  "terminal":  "sh",
  "parameters": ["--login", "-i"]
}
```

**Comment by shivapoudel** [comment]
@twolfson Good known!

**Comment by twolfson** [comment]
I am going to guess the `terminal` worked. Cool =)

I was worried that it would launch a `cmd` and then launch `msysgit` in another window from there.

**Comment by shivapoudel** [comment]
It directly launched the git bash terminal :)

**Comment by twolfson** [comment]
Good to know, thanks =)
