### ISSUE TITLE
Not opening/directory-changing in elementaryOS

### ISSUE THREAD

**Issue by Mehdi-Hp** [wbond/sublime_terminal#77]
#### It is not working in elementaryOS.  

I can fix **opening** issue with `"terminal": "pantheon-terminal"`, but I can't figure out how to fix the **change directory** issue.
For now and with empty `parameters` in setting, terminal opens in `/`

**Comment by ryukinix** [comment]
I have the same problem!

**Comment by ryukinix** [comment]
Wow! I fix that problem with add two lines before the call of terminal in main code Terminal.py.

```python
#fixing for elementaryOS
args.append('-w') #the argument to open in working directory 
args.append(cwd) #the path will open the terminal

subprocess.Popen(args, cwd=cwd)
```

It's work fine here!

**Comment by twolfson** [comment]
In #81, we discussed this further and it seems like adding `parameters: ['-w']` to your "Terminal: Settings (User)" settings should resolve the issue:

```json
{
  "terminal": "pantheon-terminal",
  "parameters": ["-w"]
}
```
