### ISSUE TITLE
Hyphen instead of dash in "Settings - More"

### ISSUE THREAD

**Issue by chairborne** [wbond/sublime_terminal#83]
As the title says, there's a mistype in the settings menu.
![2015-07-05_16-13-34](https://cloud.githubusercontent.com/assets/12383418/8511466/f454087e-2330-11e5-99d0-b785c26fbd85.png)

**Comment by twolfson** [comment]
Whoops, nice catch. We will patch that right up.

**Comment by twolfson** [comment]
This has been patched/released in `1.7.1`. Thanks for the bug report =)
