### ISSUE TITLE
[Critical] Terminal opens the different project folder

### ISSUE THREAD

**Issue by shivapoudel** [wbond/sublime_terminal#86]
If I have a directory structure like this: https://cloudup.com/cJXI9jHaDMF

```
--> Plugins ( Main Directory )
	-- axiscomposer
		- axiscomposer.php
	-- axiscomposer-iconfont
		- axiscomposer-iconfont.php
```

Now if I will add the two project from above `Plugins` sub-diectories like this:

```
-- axiscomposer
	- axiscomposer.php
-- axiscomposer-iconfont
	- axiscomposer-iconfont.php
```

How to figure out the bug:
- I will open the file `axiscomposer-iconfont.php` from second project folder.
- Now I will use the key `ctrl+shift+alt+t` to open root project folder in terminal.
- OOPS Terminal shows the folder of first project instead of the second project.

Remember `axiscomposer-iconfont.php` is second project file and which using the `ctrl+shift+alt+t`,
Terminal index read it as of first project file and opens the root folder of first project. This happens if I have the directory and project with names like `axiscomposer`, `axiscomposer-iconfont`. IMO this is due to `axiscomposer-*` names in the directory.

**Comment by twolfson** [comment]
Can you please provide examples what the "first" and "second" project folders are? I see them in the example but it's not clear which one we are referring to when you are walking through the steps.

**Comment by shivapoudel** [comment]
@twolfson very easy, you have already seen the plugins folder. So the the first folder called `axiscomposer` is added as the first project and the second `axiscomposer-iconfont` is added as the second project. If the file of second project called `axiscomposer-iconfont.php` is open and using the key `ctrl+shift+alt+t` if we open the terminal then the indexed root folder will be `axiscomposer` insead of `axiscomposer-iconfont`.

**Comment by twolfson** [comment]
Ah, I have reproduced the issue. You are correct, we are being very naive with our path finding mechanism and matching against the start of the string so we match

```
/home/todd/github/gist-sublime-terminal-86/Plugins/axiscomposer
```

in

```
/home/todd/github/gist-sublime-terminal-86/Plugins/axiscomposer-iconfont/axiscomposer-iconfont.php
```

**Comment by twolfson** [comment]
We added a patch in #87 and it has been released in `1.7.2`. It might take some time for Package Control to pick up the new tag. However, if it is not fixed within 24 hours from now, please let us know. Thanks for the bug report!

**Comment by shivapoudel** [comment]
@twolfson I am going to test this right now :P

**Comment by shivapoudel** [comment]
@twolfson yummy, #87 fixed the issue :sparkling_heart:
