### ISSUE TITLE
Local variable getting referenced before assignment

### ISSUE THREAD

**Issue by kristallizer** [wbond/sublime_terminal#9]
The following error pops up after installing the 'sublime-terminal' package in Sublime Text and trying to fire up a terminal: 

<pre>Terminal: local variable 'default' referenced before assignment</pre>

I am on Lubuntu 11.10 which uses the [Openbox] (http://openbox.org/) window manager.

**Comment by twolfson** [comment]
After scanning through the source code, it looks like `default` isn't used improperly any more. It was prob fixed since this issue was opened. Closing this issue.
