### ISSUE TITLE
Working with SublimeText 3 and Guake

### ISSUE THREAD

**Issue by Voidi** [wbond/sublime_terminal#97]
As the Readme says nothing about that: is this Plugin working with SublimeText 3?
And if, how to get it working with the Guake Terminal?

Here is what write to sublime keymap, and changed the terminal setting to "guake".

`{ 
	"keys": ["ctrl+alt+t"],
	"command": "open_terminal",
	"args": {
		"parameters": ["-n", "%CWD%"]
	}
},`

This toggles the visibilty of guake, but didn't open a new tab.

**Comment by twolfson** [comment]
Yes, this plugin will work with ST3. That's documented by Package Control but we should update the README to be less version specific =)

https://packagecontrol.io/packages/Terminal

It sounds like you are on the right track since `guake` is getting activated. Can you paste the settings you are using for Terminal? (where you changed the terminal setting to "guake")

**Comment by Voidi** [comment]
`{
	// The command to execute for the terminal, leave blank for the OS default
	// On OS X the terminal can be set to iTerm.sh to execute iTerm
	"terminal": "guake",

	// A list of default parameters to pass to the terminal, this can be
	// overridden by passing the "parameters" key with a list value to the args
	// dict when calling the "open_terminal" or "open_terminal_project_folder"
	// commands
	"parameters": []
}`

The key configuration doesn't deactive the old standard, only adds my combination.

Another questions: change the settings in the keymap the arguments for activation via right click?

**Comment by twolfson** [comment]
Ah, I see the issue. Key bindings should not be receiving the requested parameters for executing the terminal. Instead, those should be stored under `parameters` in the `Terminal` settings. Try updating your configurations to the following:

```js
// Key bindings
{ "keys": ["ctrl+alt+t"], "command": "open_terminal"}

// Terminal configuration
{
  "terminal": "guake",
  "parameters": ["-n", "%CWD%"]
}
```

**Comment by Voidi** [comment]
Thanks, now it works.

**Comment by twolfson** [comment]
That's great to hear =)
